In [4]:
import numpy as np
import pandas as pd

In [5]:
movies = pd.read_csv('../datasets/tmdb_5000_movies.csv')
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [6]:
movies = movies[['id','title','vote_average','popularity']]

In [7]:
movies.head(1)

      id   title  vote_average  popularity
0  19995  Avatar           7.2  150.437577

In [8]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()

rating = mms.fit_transform(movies.iloc[:,2:])

In [9]:
rating

array([[0.72      , 0.17181451],
       [0.69      , 0.15884603],
       [0.63      , 0.12263486],
       ...,
       [0.7       , 0.00164973],
       [0.57      , 0.00097879],
       [0.63      , 0.00220412]], shape=(4803, 2))

In [10]:
import pickle
pickle.dump(rating,open('rating.pkl','wb'))