In [25]:
import numpy as np
import pandas as pd

In [26]:
movies = pd.read_csv('../datasets/tmdb_5000_movies.csv')
credits = pd.read_csv('../datasets/tmdb_5000_credits.csv')
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [27]:
credits = credits.rename(columns={'movie_id':"id"})
credits.head(1)

,id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [28]:
movies.shape,credits.shape

((4803, 20), (4803, 4))

In [29]:
movies = movies.merge(credits,on='id')
movies.shape

(4803, 23)

In [30]:
movies.head(1)
movies = movies.rename(columns={'title_x':'title'})

In [31]:
''' 
genre
id
keywords
title_x
overview
cast
crew
'''

movies = movies[['id','title','overview','genres','keywords','cast','crew','vote_average','vote_count','popularity',"release_date","runtime","original_language"]]

In [32]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 4803 non-null   int64
 1   title              4803 non-null   object
 2   overview           4800 non-null   object
 3   genres             4803 non-null   object
 4   keywords           4803 non-null   object
 5   cast               4803 non-null   object
 6   crew               4803 non-null   object
 7   vote_average       4803 non-null   float64
 8   vote_count         4803 non-null   int64
 9   popularity         4803 non-null   float64
 10  release_date       4802 non-null   object
 11  runtime            4801 non-null   float64
 12  original_language  4803 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 487.9+ KB

In [33]:
movies.head()

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity,release_date,runtime,original_language
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2,11800,150.437577,2009-12-10,162.0,en
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.9,4500,139.082615,2007-05-19,169.0,en
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3,4466,107.376788,2015-10-26,148.0,en
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.6,9106,112.312950,2012-07-16,165.0,en
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1,2124,43.926995,2012-03-07,132.0,en

In [34]:
movies["overview"] = movies["overview"].fillna("")
movies.runtime = movies.runtime.fillna(0)
movies.release_date = movies.release_date.fillna("")
movies["release_year"] = (
    pd.to_datetime(
        movies["release_date"],
        errors="coerce"
    )
    .dt.year
    .fillna(0)
    .astype(int)
)

In [ ]:
movies.isnull().sum()

id                   0
title                0
overview             0
genres               0
keywords             0
cast                 0
crew                 0
vote_average         0
vote_count           0
popularity           0
release_date         0
runtime              0
original_language    0
release_year         0
dtype: int64

In [43]:
movies.head(1)

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity,release_date,runtime,original_language,release_year
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy ScienceFiction,cultureclash future spacewar spacecolony socie...,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2,11800,150.437577,2009-12-10,162.0,en,2009

In [51]:
import pickle
pickle.dump(
    movies,
    open(
        "../recommendation/models/movie_metadata.pkl",
        "wb"
    )
)

In [37]:
movies.dropna(inplace=True)

In [38]:
movies.duplicated().sum()

np.int64(0)

In [40]:
import ast

In [41]:
def convert(obj):
    li = []
    for i in ast.literal_eval(obj):
        li.append(i['name'].replace(" ",""))
    return ' '.join(li)

In [42]:
movies['genres'] = movies.genres.apply(convert)
movies['keywords'] = movies.keywords.apply(convert)

In [209]:
movies.isnull().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [210]:
movies

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy ScienceFiction,cultureclash future spacewar spacecolony socie...,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,ocean drugabuse exoticisland eastindiatradingc...,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,spy basedonnovel secretagent sequel mi6 britis...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,dccomics crimefighter terrorist secretidentity...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure ScienceFiction,basedonnovel mars medallion spacetravel prince...,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,Action Crime Thriller,unitedstates–mexicobarrier legs arms paperknif...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,Comedy Romance,,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",Comedy Drama Romance TVMovie,date loveatfirstsight narration investigation ...,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,,,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,Documentary,obsession camcorder crush dreamgirl,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [44]:
def convert3(obj):
    li = []
    count = 0
    for i in ast.literal_eval(obj):
        if(count>=3): break
        li.append(i['name'].replace(" ",""))
        count +=1
    return ' '.join(li)

In [45]:
movies.cast = movies.cast.apply(convert3)

In [46]:
movies

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity,release_date,runtime,original_language,release_year
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy ScienceFiction,cultureclash future spacewar spacecolony socie...,SamWorthington ZoeSaldana SigourneyWeaver,"[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",7.2,11800,150.437577,2009-12-10,162.0,en,2009
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,ocean drugabuse exoticisland eastindiatradingc...,JohnnyDepp OrlandoBloom KeiraKnightley,"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",6.9,4500,139.082615,2007-05-19,169.0,en,2007
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,spy basedonnovel secretagent sequel mi6 britis...,DanielCraig ChristophWaltz LéaSeydoux,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",6.3,4466,107.376788,2015-10-26,148.0,en,2015
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,dccomics crimefighter terrorist secretidentity...,ChristianBale MichaelCaine GaryOldman,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",7.6,9106,112.312950,2012-07-16,165.0,en,2012
4,49529,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure ScienceFiction,basedonnovel mars medallion spacetravel prince...,TaylorKitsch LynnCollins SamanthaMorton,"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",6.1,2124,43.926995,2012-03-07,132.0,en,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,Action Crime Thriller,unitedstates–mexicobarrier legs arms paperknif...,CarlosGallardo JaimedeHoyos PeterMarquardt,"[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",6.6,238,14.269792,1992-09-04,81.0,es,1992
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,Comedy Romance,,EdwardBurns KerryBishé MarshaDietlein,"[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",5.9,5,0.642552,2011-12-26,85.0,en,2011
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",Comedy Drama Romance TVMovie,date loveatfirstsight narration investigation ...,EricMabius KristinBooth CrystalLowe,"[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...",7.0,6,1.444476,2013-10-13,120.0,en,2013
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,,,DanielHenney ElizaCoupe BillPaxton,"[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",5.7,7,0.857008,2012-05-03,98.0,en,2012
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,Documentary,obsession camcorder crush dreamgirl,DrewBarrymore BrianHerzlinger CoreyFeldman,"[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",6.3,16,1.929883,2005-08-05,90.0,en,2005

In [47]:
def convertcrew(obj):
    li = []
    for i in ast.literal_eval(obj):
        if(i['job'] == 'Director'):
            li.append(i['name'].replace(" ",""))
            break
    return ' '.join(li)

In [48]:
movies.crew = movies.crew.apply(convertcrew)
movies

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity,release_date,runtime,original_language,release_year
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy ScienceFiction,cultureclash future spacewar spacecolony socie...,SamWorthington ZoeSaldana SigourneyWeaver,JamesCameron,7.2,11800,150.437577,2009-12-10,162.0,en,2009
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,ocean drugabuse exoticisland eastindiatradingc...,JohnnyDepp OrlandoBloom KeiraKnightley,GoreVerbinski,6.9,4500,139.082615,2007-05-19,169.0,en,2007
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,spy basedonnovel secretagent sequel mi6 britis...,DanielCraig ChristophWaltz LéaSeydoux,SamMendes,6.3,4466,107.376788,2015-10-26,148.0,en,2015
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,dccomics crimefighter terrorist secretidentity...,ChristianBale MichaelCaine GaryOldman,ChristopherNolan,7.6,9106,112.312950,2012-07-16,165.0,en,2012
4,49529,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure ScienceFiction,basedonnovel mars medallion spacetravel prince...,TaylorKitsch LynnCollins SamanthaMorton,AndrewStanton,6.1,2124,43.926995,2012-03-07,132.0,en,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,Action Crime Thriller,unitedstates–mexicobarrier legs arms paperknif...,CarlosGallardo JaimedeHoyos PeterMarquardt,RobertRodriguez,6.6,238,14.269792,1992-09-04,81.0,es,1992
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,Comedy Romance,,EdwardBurns KerryBishé MarshaDietlein,EdwardBurns,5.9,5,0.642552,2011-12-26,85.0,en,2011
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",Comedy Drama Romance TVMovie,date loveatfirstsight narration investigation ...,EricMabius KristinBooth CrystalLowe,ScottSmith,7.0,6,1.444476,2013-10-13,120.0,en,2013
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,,,DanielHenney ElizaCoupe BillPaxton,DanielHsia,5.7,7,0.857008,2012-05-03,98.0,en,2012
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,Documentary,obsession camcorder crush dreamgirl,DrewBarrymore BrianHerzlinger CoreyFeldman,BrianHerzlinger,6.3,16,1.929883,2005-08-05,90.0,en,2005

In [49]:
movies.overview = movies.overview.apply(lambda x:' '.join(x.split()))

In [50]:
movies

,id,title,overview,genres,keywords,cast,crew,vote_average,vote_count,popularity,release_date,runtime,original_language,release_year
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy ScienceFiction,cultureclash future spacewar spacecolony socie...,SamWorthington ZoeSaldana SigourneyWeaver,JamesCameron,7.2,11800,150.437577,2009-12-10,162.0,en,2009
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,ocean drugabuse exoticisland eastindiatradingc...,JohnnyDepp OrlandoBloom KeiraKnightley,GoreVerbinski,6.9,4500,139.082615,2007-05-19,169.0,en,2007
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,spy basedonnovel secretagent sequel mi6 britis...,DanielCraig ChristophWaltz LéaSeydoux,SamMendes,6.3,4466,107.376788,2015-10-26,148.0,en,2015
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,dccomics crimefighter terrorist secretidentity...,ChristianBale MichaelCaine GaryOldman,ChristopherNolan,7.6,9106,112.312950,2012-07-16,165.0,en,2012
4,49529,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure ScienceFiction,basedonnovel mars medallion spacetravel prince...,TaylorKitsch LynnCollins SamanthaMorton,AndrewStanton,6.1,2124,43.926995,2012-03-07,132.0,en,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,Action Crime Thriller,unitedstates–mexicobarrier legs arms paperknif...,CarlosGallardo JaimedeHoyos PeterMarquardt,RobertRodriguez,6.6,238,14.269792,1992-09-04,81.0,es,1992
4799,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,Comedy Romance,,EdwardBurns KerryBishé MarshaDietlein,EdwardBurns,5.9,5,0.642552,2011-12-26,85.0,en,2011
4800,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",Comedy Drama Romance TVMovie,date loveatfirstsight narration investigation ...,EricMabius KristinBooth CrystalLowe,ScottSmith,7.0,6,1.444476,2013-10-13,120.0,en,2013
4801,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,,,DanielHenney ElizaCoupe BillPaxton,DanielHsia,5.7,7,0.857008,2012-05-03,98.0,en,2012
4802,25975,My Date with Drew,Ever since the second grade when he first saw ...,Documentary,obsession camcorder crush dreamgirl,DrewBarrymore BrianHerzlinger CoreyFeldman,BrianHerzlinger,6.3,16,1.929883,2005-08-05,90.0,en,2005

In [218]:
movies['tags'] = movies.overview + ' ' + movies.genres + ' '+ movies.genres +' '+ movies.genres + ' '+ movies.keywords + ' '+ movies.keywords + ' '+ movies.cast + ' '+ movies.cast+' '+movies.crew+' '+movies.crew+' '+movies.crew+' '

In [219]:
print(movies['tags'][0])

In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction Action Adventure Fantasy ScienceFiction Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver SamWorthington ZoeSaldana SigourneyWeaver JamesCameron JamesCameron JamesCameron

In [220]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [221]:
def stem(text):
    y = [ps.stem(i) for i in text.split()]
    return ' '.join(y)

In [222]:
movies.tags = movies.tags.apply(stem)

In [223]:
movies = movies[['id','title','tags']]

In [224]:
movies.tags = movies.tags.apply(lambda x: x.lower())
movies

/var/folders/2w/b0wrwgn94f34mb0ym0y1pwq00000gn/T/ipykernel_10017/2185481884.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.tags = movies.tags.apply(lambda x: x.lower())

,id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4798,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4799,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4800,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4801,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4802,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [225]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [226]:
vectors = cv.fit_transform(movies.tags).toarray()

In [242]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.20300178, 0.18122009, ..., 0.06745593, 0.        ,
        0.        ],
       [0.20300178, 1.        , 0.17780868, ..., 0.00919251, 0.        ,
        0.01178675],
       [0.18122009, 0.17780868, 1.        , ..., 0.01107833, 0.        ,
        0.        ],
       ...,
       [0.06745593, 0.00919251, 0.01107833, ..., 1.        , 0.02962069,
        0.03965604],
       [0.        , 0.        , 0.        , ..., 0.02962069, 1.        ,
        0.07596002],
       [0.        , 0.01178675, 0.        , ..., 0.03965604, 0.07596002,
        1.        ]], shape=(4800, 4800))

In [228]:
def recommend(movie,similarity):
    idx = movies[movies['title']==movie].index[0]
    distances = sorted(list(enumerate(similarity[idx])),reverse=True,key=lambda x:x[1])[1:6]
    for i in distances:
        print(movies.iloc[i[0]].title)

In [229]:
recommend('The Dark Knight',similarity)

The Dark Knight Rises
Batman Begins
Amidst the Devil's Wings
Point Blank
In Too Deep

In [230]:
movies[['id','title']].to_csv('vectorized_movies.csv',index=False)

In [231]:
import pickle
pickle.dump(similarity,open('similarity.pkl','wb'))

In [232]:
df = pd.read_csv('movie_titles.csv')
df

          id                                     title
0      19995                                    Avatar
1        285  Pirates of the Caribbean: At World's End
2     206647                                   Spectre
3      49026                     The Dark Knight Rises
4      49529                               John Carter
...      ...                                       ...
4795    9367                               El Mariachi
4796   72766                                 Newlyweds
4797  231617                 Signed, Sealed, Delivered
4798  126186                          Shanghai Calling
4799   25975                         My Date with Drew

[4800 rows x 2 columns]

In [233]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_id = TfidfVectorizer(max_features=5000,stop_words='english')

In [234]:
tf_vectors = tf_id.fit_transform(movies.tags).toarray()
tf_similarity = cosine_similarity(tf_vectors)

In [235]:
tf_similarity

array([[1.        , 0.05195354, 0.04889476, ..., 0.0277813 , 0.        ,
        0.        ],
       [0.05195354, 1.        , 0.03894686, ..., 0.00712195, 0.        ,
        0.00293863],
       [0.04889476, 0.03894686, 1.        , ..., 0.00858833, 0.        ,
        0.        ],
       ...,
       [0.0277813 , 0.00712195, 0.00858833, ..., 1.        , 0.01580595,
        0.03455738],
       [0.        , 0.        , 0.        , ..., 0.01580595, 1.        ,
        0.01824812],
       [0.        , 0.00293863, 0.        , ..., 0.03455738, 0.01824812,
        1.        ]], shape=(4800, 4800))

In [236]:
recommend('The Dark Knight',tf_similarity)

The Dark Knight Rises
Batman Begins
Batman Returns
Batman v Superman: Dawn of Justice
Batman & Robin

In [ ]:
movie_to_index = pd.Series(movies.index, index=movies['title']).to_dict()
movie_to_index

{'Avatar': 0,
 "Pirates of the Caribbean: At World's End": 1,
 'Spectre': 2,
 'The Dark Knight Rises': 3,
 'John Carter': 4,
 'Spider-Man 3': 5,
 'Tangled': 6,
 'Avengers: Age of Ultron': 7,
 'Harry Potter and the Half-Blood Prince': 8,
 'Batman v Superman: Dawn of Justice': 9,
 'Superman Returns': 10,
 'Quantum of Solace': 11,
 "Pirates of the Caribbean: Dead Man's Chest": 12,
 'The Lone Ranger': 13,
 'Man of Steel': 14,
 'The Chronicles of Narnia: Prince Caspian': 15,
 'The Avengers': 16,
 'Pirates of the Caribbean: On Stranger Tides': 17,
 'Men in Black 3': 18,
 'The Hobbit: The Battle of the Five Armies': 19,
 'The Amazing Spider-Man': 20,
 'Robin Hood': 21,
 'The Hobbit: The Desolation of Smaug': 22,
 'The Golden Compass': 23,
 'King Kong': 24,
 'Titanic': 25,
 'Captain America: Civil War': 26,
 'Battleship': 27,
 'Jurassic World': 28,
 'Skyfall': 29,
 'Spider-Man 2': 30,
 'Iron Man 3': 31,
 'Alice in Wonderland': 32,
 'X-Men: The Last Stand': 33,
 'Monsters University': 34,
 'Transformers: Revenge of the Fallen': 35,
 'Transformers: Age of Extinction': 36,
 'Oz: The Great and Powerful': 37,
 'The Amazing Spider-Man 2': 38,
 'TRON: Legacy': 39,
 'Cars 2': 40,
 'Green Lantern': 41,
 'Toy Story 3': 42,
 'Terminator Salvation': 43,
 'Furious 7': 44,
 'World War Z': 45,
 'X-Men: Days of Future Past': 46,
 'Star Trek Into Darkness': 47,
 'Jack the Giant Slayer': 48,
 'The Great Gatsby': 49,
 'Prince of Persia: The Sands of Time': 50,
 'Pacific Rim': 51,
 'Transformers: Dark of the Moon': 52,
 'Indiana Jones and the Kingdom of the Crystal Skull': 53,
 'The Good Dinosaur': 54,
 'Brave': 55,
 'Star Trek Beyond': 56,
 'WALL·E': 57,
 'Rush Hour 3': 58,
 '2012': 59,
 'A Christmas Carol': 60,
 'Jupiter Ascending': 61,
 'The Legend of Tarzan': 62,
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe': 63,
 'X-Men: Apocalypse': 64,
 'The Dark Knight': 65,
 'Up': 66,
 'Monsters vs Aliens': 67,
 'Iron Man': 68,
 'Hugo': 69,
 'Wild Wild West': 70,
 'The Mummy: Tomb of the Dragon Emperor': 71,
 'Suicide Squad': 72,
 'Evan Almighty': 73,
 'Edge of Tomorrow': 74,
 'Waterworld': 75,
 'G.I. Joe: The Rise of Cobra': 76,
 'Inside Out': 77,
 'The Jungle Book': 78,
 'Iron Man 2': 79,
 'Snow White and the Huntsman': 80,
 'Maleficent': 81,
 'Dawn of the Planet of the Apes': 82,
 'The Lovers': 83,
 '47 Ronin': 84,
 'Captain America: The Winter Soldier': 85,
 'Shrek Forever After': 86,
 'Tomorrowland': 87,
 'Big Hero 6': 88,
 'Wreck-It Ralph': 89,
 'The Polar Express': 90,
 'Independence Day: Resurgence': 91,
 'How to Train Your Dragon': 92,
 'Terminator 3: Rise of the Machines': 93,
 'Guardians of the Galaxy': 94,
 'Interstellar': 95,
 'Inception': 96,
 'Shin Godzilla': 97,
 'The Hobbit: An Unexpected Journey': 98,
 'The Fast and the Furious': 99,
 'The Curious Case of Benjamin Button': 100,
 'X-Men: First Class': 101,
 'The Hunger Games: Mockingjay - Part 2': 102,
 "The Sorcerer's Apprentice": 103,
 'Poseidon': 104,
 'Alice Through the Looking Glass': 105,
 'Shrek the Third': 106,
 'Warcraft': 107,
 'Terminator Genisys': 108,
 'The Chronicles of Narnia: The Voyage of the Dawn Treader': 109,
 'Pearl Harbor': 110,
 'Transformers': 111,
 'Alexander': 112,
 'Harry Potter and the Order of the Phoenix': 113,
 'Harry Potter and the Goblet of Fire': 114,
 'Hancock': 115,
 'I Am Legend': 116,
 'Charlie and the Chocolate Factory': 117,
 'Ratatouille': 118,
 'Batman Begins': 119,
 'Madagascar: Escape 2 Africa': 120,
 'Night at the Museum: Battle of the Smithsonian': 121,
 'X-Men Origins: Wolverine': 122,
 'The Matrix Revolutions': 123,
 'Frozen': 124,
 'The Matrix Reloaded': 125,
 'Thor: The Dark World': 126,
 'Mad Max: Fury Road': 127,
 'Angels & Demons': 128,
 'Thor': 129,
 'Bolt': 130,
 'G-Force': 131,
 'Wrath of the Titans': 132,
 'Dark Shadows': 133,
 'Mission: Impossible - Rogue Nation': 134,
 'The Wolfman': 135,
 'Bee Movie': 136,
 'Kung Fu Panda 2': 137,
 'The Last Airbender': 138,
 'Mission: Impossible III': 139,
 'White House Down': 140,
 'Mars Needs Moms': 141,
 'Flushed Away': 142,
 'Pan': 143,
 'Mr. Peabody & Sherman': 144,
 'Troy': 145,
 "Madagascar 3: Europe's Most Wanted": 146,
 'Die Another Day': 147,
 'Ghostbusters': 148,
 'Armageddon': 149,
 'Men in Black II': 150,
 'Beowulf': 151,
 'Kung Fu Panda 3': 152,
 'Mission: Impossible - Ghost Protocol': 153,
 'Rise of the Guardians': 154,
 'Fun with Dick and Jane': 155,
 'The Last Samurai': 156,
 'Exodus: Gods and Kings': 157,
 'Star Trek': 158,
 'Spider-Man': 159,
 'How to Train Your Dragon 2': 160,
 'Gods of Egypt': 161,
 'Stealth': 162,
 'Watchmen': 163,
 'Lethal Weapon 4': 164,
 'Hulk': 165,
 'G.I. Joe: Retaliation': 166,
 'Sahara': 167,
 'Final Fantasy: The Spirits Within': 168,
 'Captain America: The First Avenger': 169,
 'The World Is Not Enough': 170,
 'Master and Commander: The Far Side of the World': 171,
 'The Twilight Saga: Breaking Dawn - Part 2': 172,
 'Happy Feet Two': 173,
 'The Incredible Hulk': 174,
 'The BFG': 175,
 'The Revenant': 176,
 'Turbo': 177,
 'Rango': 178,
 'Penguins of Madagascar': 179,
 'The Bourne Ultimatum': 180,
 'Kung Fu Panda': 181,
 'Ant-Man': 182,
 'The Hunger Games: Catching Fire': 183,
 'Home': 184,
 'War of the Worlds': 185,
 'Bad Boys II': 186,
 'Puss in Boots': 187,
 'Salt': 188,
 'Noah': 189,
 'The Adventures of Tintin': 190,
 'Harry Potter and the Prisoner of Azkaban': 191,
 'Australia': 192,
 'After Earth': 193,
 'Dinosaur': 194,
 'Night at the Museum: Secret of the Tomb': 195,
 'Megamind': 196,
 "Harry Potter and the Philosopher's Stone": 197,
 'R.I.P.D.': 198,
 'Pirates of the Caribbean: The Curse of the Black Pearl': 199,
 'The Hunger Games: Mockingjay - Part 1': 200,
 'The Da Vinci Code': 201,
 'Rio 2': 202,
 'X2': 203,
 'Fast Five': 204,
 'Sherlock Holmes: A Game of Shadows': 205,
 'Clash of the Titans': 206,
 'Total Recall': 207,
 'The 13th Warrior': 208,
 'The Bourne Legacy': 209,
 'Batman & Robin': 210,
 'How the Grinch Stole Christmas': 211,
 'The Day After Tomorrow': 212,
 'Mission: Impossible II': 213,
 'The Perfect Storm': 214,
 'Fantastic 4: Rise of the Silver Surfer': 215,
 'Life of Pi': 216,
 'Ghost Rider': 217,
 'Jason Bourne': 218,
 "Charlie's Angels: Full Throttle": 219,
 'Prometheus': 220,
 'Stuart Little 2': 221,
 'Elysium': 222,
 'The Chronicles of Riddick': 223,
 'RoboCop': 224,
 'Speed Racer': 225,
 'How Do You Know': 226,
 'Knight and Day': 227,
 'Oblivion': 228,
 'Star Wars: Episode III - Revenge of the Sith': 229,
 'Star Wars: Episode II - Attack of the Clones': 230,
 'Monsters, Inc.': 231,
 'The Wolverine': 232,
 'Star Wars: Episode I - The Phantom Menace': 233,
 'The Croods': 234,
 'Asterix at the Olympic Games': 235,
 'Windtalkers': 236,
 "The Huntsman: Winter's War": 237,
 'Teenage Mutant Ninja Turtles': 238,
 'Gravity': 239,
 "Dante's Peak": 240,
 'Teenage Mutant Ninja Turtles: Out of the Shadows': 241,
 'Fantastic Four': 242,
 'Night at the Museum': 243,
 'San Andreas': 244,
 'Tomorrow Never Dies': 245,
 'The Patriot': 246,
 "Ocean's Twelve": 247,
 'Mr. & Mrs. Smith': 248,
 'Insurgent': 249,
 'The Aviator': 250,
 "Gulliver's Travels": 251,
 'The Green Hornet': 252,
 '300: Rise of an Empire': 253,
 'The Smurfs': 254,
 'Home on the Range': 255,
 'Allegiant': 256,
 'Real Steel': 257,
 'The Smurfs 2': 258,
 'Speed 2: Cruise Control': 259,
 "Ender's Game": 260,
 'Live Free or Die Hard': 261,
 'The Lord of the Rings: The Fellowship of the Ring': 262,
 'Around the World in 80 Days': 263,
 'Ali': 264,
 'The Cat in the Hat': 265,
 'I, Robot': 266,
 'Kingdom of Heaven': 267,
 'Stuart Little': 268,
 'The Princess and the Frog': 269,
 'The Martian': 270,
 'The Island': 271,
 'Town & Country': 272,
 'Gone in Sixty Seconds': 273,
 'Gladiator': 274,
 'Minority Report': 275,
 'Harry Potter and the Chamber of Secrets': 276,
 'Casino Royale': 277,
 'Planet of the Apes': 278,
 'Terminator 2: Judgment Day': 279,
 'Public Enemies': 280,
 'American Gangster': 281,
 'True Lies': 282,
 'The Taking of Pelham 1 2 3': 283,
 'Little Fockers': 284,
 'The Other Guys': 285,
 'Eraser': 286,
 'Django Unchained': 287,
 'The Hunchback of Notre Dame': 288,
 "The Emperor's New Groove": 289,
 'The Expendables 2': 290,
 'National Treasure': 291,
 'Eragon': 292,
 'Where the Wild Things Are': 293,
 'Epic': 294,
 'The Tourist': 295,
 'End of Days': 296,
 'Blood Diamond': 297,
 'The Wolf of Wall Street': 298,
 'Batman Forever': 299,
 'Starship Troopers': 300,
 'Cloud Atlas': 301,
 "Legend of the Guardians: The Owls of Ga'Hoole": 302,
 'Catwoman': 303,
 'Hercules': 304,
 'Treasure Planet': 305,
 'Land of the Lost': 306,
 'The Expendables 3': 307,
 'Point Break': 308,
 'Son of the Mask': 309,
 'In the Heart of the Sea': 310,
 'The Adventures of Pluto Nash': 311,
 'Green Zone': 312,
 'The Peanuts Movie': 313,
 'The Spanish Prisoner': 314,
 'The Mummy Returns': 315,
 'Gangs of New York': 316,
 'The Flowers of War': 317,
 "Surf's Up": 318,
 'The Stepford Wives': 319,
 'Black Hawk Down': 320,
 'The Campaign': 321,
 'The Fifth Element': 322,
 'Sex and the City 2': 323,
 'The Road to El Dorado': 324,
 'Ice Age: Continental Drift': 325,
 'Cinderella': 326,
 'The Lovely Bones': 327,
 'Finding Nemo': 328,
 'The Lord of the Rings: The Return of the King': 329,
 'The Lord of the Rings: The Two Towers': 330,
 'Seventh Son': 331,
 'Lara Croft: Tomb Raider': 332,
 'Transcendence': 333,
 'Jurassic Park III': 334,
 'Rise of the Planet of the Apes': 335,
 'The Spiderwick Chronicles': 336,
 'A Good Day to Die Hard': 337,
 'The Alamo': 338,
 'The Incredibles': 339,
 'Cutthroat Island': 340,
 'Percy Jackson & the Olympians: The Lightning Thief': 341,
 'Men in Black': 342,
 'Toy Story 2': 343,
 'Unstoppable': 344,
 'Rush Hour 2': 345,
 'What Lies Beneath': 346,
 'Cloudy with a Chance of Meatballs': 347,
 'Ice Age: Dawn of the Dinosaurs': 348,
 'The Secret Life of Walter Mitty': 349,
 "Charlie's Angels": 350,
 'The Departed': 351,
 'Mulan': 352,
 'Tropic Thunder': 353,
 'The Girl with the Dragon Tattoo': 354,
 'Die Hard: With a Vengeance': 355,
 'Sherlock Holmes': 356,
 'Ben-Hur': 357,
 'Atlantis: The Lost Empire': 358,
 'Alvin and the Chipmunks: The Road Chip': 359,
 'Valkyrie': 360,
 "You Don't Mess with the Zohan": 361,
 'Pixels': 362,
 'A.I. Artificial Intelligence': 363,
 'The Haunted Mansion': 364,
 'Contact': 365,
 'Hollow Man': 366,
 'The Interpreter': 367,
 'Percy Jackson: Sea of Monsters': 368,
 'Lara Croft Tomb Raider: The Cradle of Life': 369,
 'Now You See Me 2': 370,
 'The Saint': 371,
 'Spy Game': 372,
 'Mission to Mars': 373,
 'Rio': 374,
 'Bicentennial Man': 375,
 'Volcano': 376,
 "The Devil's Own": 377,
 'K-19: The Widowmaker': 378,
 'Conan the Barbarian': 379,
 'Cinderella Man': 380,
 'The Nutcracker: The Untold Story': 381,
 'Seabiscuit': 382,
 'Twister': 383,
 'Cast Away': 384,
 'Happy Feet': 385,
 'The Bourne Supremacy': 386,
 'Air Force One': 387,
 "Ocean's Eleven": 388,
 'The Three Musketeers': 389,
 'Hotel Transylvania': 390,
 'Enchanted': 391,
 'Safe House': 392,
 '102 Dalmatians': 393,
 'Tower Heist': 394,
 'The Holiday': 395,
 'Enemy of the State': 396,
 "It's Complicated": 397,
 "Ocean's Thirteen": 398,
 'Open Season': 399,
 'Divergent': 400,
 'Enemy at the Gates': 401,
 'The Rundown': 402,
 'Last Action Hero': 403,
 'Memoirs of a Geisha': 404,
 'The Fast and the Furious: Tokyo Drift': 405,
 'Arthur Christmas': 406,
 'Meet Joe Black': 407,
 'Collateral Damage': 408,
 'All That Jazz': 409,
 'Mirror Mirror': 410,
 'Scott Pilgrim vs. the World': 411,
 'The Core': 412,
 'Nutty Professor II: The Klumps': 413,
 'Scooby-Doo': 414,
 'Dredd': 415,
 'Click': 416,
 'Creepshow': 417,
 'Cats & Dogs 2 : The Revenge of Kitty Galore': 418,
 'Jumper': 419,
 'Hellboy II: The Golden Army': 420,
 'Zodiac': 421,
 'The 6th Day': 422,
 'Bruce Almighty': 423,
 'The Expendables': 424,
 'Mission: Impossible': 425,
 'The Hunger Games': 426,
 'The Hangover Part II': 427,
 'Batman Returns': 428,
 'Over the Hedge': 429,
 'Lilo & Stitch': 430,
 "Charlotte's Web": 431,
 'Deep Impact': 432,
 'RED 2': 433,
 'The Longest Yard': 434,
 'Alvin and the Chipmunks: Chipwrecked': 435,
 'Grown Ups 2': 436,
 'Get Smart': 437,
 "Something's Gotta Give": 438,
 'Shutter Island': 439,
 'Four Christmases': 440,
 'Robots': 441,
 'Face/Off': 442,
 'Bedtime Stories': 443,
 'Road to Perdition': 444,
 'Just Go with It': 445,
 'Con Air': 446,
 'Eagle Eye': 447,
 'Cold Mountain': 448,
 'The Book of Eli': 449,
 'Flubber': 450,
 'The Haunting': 451,
 'Space Jam': 452,
 'The Pink Panther': 453,
 'The Day the Earth Stood Still': 454,
 'Conspiracy Theory': 455,
 'Fury': 456,
 'Six Days Seven Nights': 457,
 'Yogi Bear': 458,
 'Spirit: Stallion of the Cimarron': 459,
 'Zookeeper': 460,
 'Lost in Space': 461,
 'The Manchurian Candidate': 462,
 'Déjà Vu': 463,
 'Hotel Transylvania 2': 464,
 'Fantasia 2000': 465,
 'The Time Machine': 466,
 'Mighty Joe Young': 467,
 'Swordfish': 468,
 'The Legend of Zorro': 469,
 'What Dreams May Come': 470,
 'Little Nicky': 471,
 'The Brothers Grimm': 472,
 'Mars Attacks!': 473,
 'Evolution': 474,
 'The Edge': 475,
 'Surrogates': 476,
 'Thirteen Days': 477,
 'Daylight': 478,
 'Walking With Dinosaurs': 479,
 'Battlefield Earth': 480,
 'Looney Tunes: Back in Action': 481,
 'Nine': 482,
 'Timeline': 483,
 'The Postman': 484,
 'Babe: Pig in the City': 485,
 'The Last Witch Hunter': 486,
 'Red Planet': 487,
 'Arthur and the Invisibles': 488,
 'Oceans': 489,
 'A Sound of Thunder': 490,
 'Pompeii': 491,
 'Top Cat Begins': 492,
 'A Beautiful Mind': 493,
 'The Lion King': 494,
 'Journey 2: The Mysterious Island': 495,
 'Cloudy with a Chance of Meatballs 2': 496,
 'Red Dragon': 497,
 'Hidalgo': 498,
 'Jack and Jill': 499,
 '2 Fast 2 Furious': 500,
 'The Little Prince': 501,
 'The Invasion': 502,
 'The Adventures of Rocky & Bullwinkle': 503,
 'The Secret Life of Pets': 504,
 'The League of Extraordinary Gentlemen': 505,
 'Despicable Me 2': 506,
 'Independence Day': 507,
 'The Lost World: Jurassic Park': 508,
 'Madagascar': 509,
 'Children of Men': 510,
 'X-Men': 511,
 'Wanted': 512,
 'The Rock': 513,
 'Ice Age: The Meltdown': 514,
 '50 First Dates': 515,
 'Hairspray': 516,
 'Exorcist: The Beginning': 517,
 'Inspector Gadget': 518,
 'Now You See Me': 519,
 'Grown Ups': 520,
 'The Terminal': 521,
 'Hotel for Dogs': 522,
 'Vertical Limit': 523,
 "Charlie Wilson's War": 524,
 'Shark Tale': 525,
 'Dreamgirls': 526,
 'Be Cool': 527,
 'Munich': 528,
 'Tears of the Sun': 529,
 'Killers': 530,
 'The Man from U.N.C.L.E.': 531,
 'Spanglish': 532,
 'Monster House': 533,
 'Bandits': 534,
 'First Knight': 535,
 'Anna and the King': 536,
 'Immortals': 537,
 'Hostage': 538,
 'Titan A.E.': 539,
 'Hollywood Homicide': 540,
 'Soldier': 541,
 'Carriers': 542,
 'Monkeybone': 543,
 'Flight of the Phoenix': 544,
 'Unbreakable': 545,
 'Minions': 546,
 'Sucker Punch': 547,
 'Snake Eyes': 548,
 'Sphere': 549,
 'The Angry Birds Movie': 550,
 "Fool's Gold": 551,
 'Funny People': 552,
 'The Kingdom': 553,
 'Talladega Nights: The Ballad of Ricky Bobby': 554,
 'Dr. Dolittle 2': 555,
 'Braveheart': 556,
 'Jarhead': 557,
 'The Simpsons Movie': 558,
 'The Majestic': 559,
 'Driven': 560,
 'Two Brothers': 561,
 'The Village': 562,
 'Doctor Dolittle': 563,
 'Signs': 564,
 'Shrek 2': 565,
 'Cars': 566,
 'Runaway Bride': 567,
 'xXx': 568,
 'The SpongeBob Movie: Sponge Out of Water': 569,
 'Ransom': 570,
 'Inglourious Basterds': 571,
 'Hook': 572,
 'Die Hard 2': 573,
 'S.W.A.T.': 574,
 'Vanilla Sky': 575,
 'Lady in the Water': 576,
 'AVP: Alien vs. Predator': 577,
 'Alvin and the Chipmunks: The Squeakquel': 578,
 'We Were Soldiers': 579,
 'Olympus Has Fallen': 580,
 'Star Trek: Insurrection': 581,
 'Battle: Los Angeles': 582,
 'Big Fish': 583,
 'Wolf': 584,
 'War Horse': 585,
 'The Monuments Men': 586,
 'The Abyss': 587,
 'Wall Street: Money Never Sleeps': 588,
 'Dracula Untold': 589,
 'The Siege': 590,
 'Stardust': 591,
 'Seven Years in Tibet': 592,
 'The Dilemma': 593,
 'Bad Company': 594,
 'Doom': 595,
 'I Spy': 596,
 'Underworld: Awakening': 597,
 'Rock of Ages': 598,
 "Hart's War": 599,
 'Killer Elite': 600,
 'Rollerball': 601,
 'Ballistic: Ecks vs. Sever': 602,
 'Hard Rain': 603,
 'Osmosis Jones': 604,
 "Legends of Oz: Dorothy's Return": 605,
 'Blackhat': 606,
 'Sky Captain and the World of Tomorrow': 607,
 'Basic Instinct 2': 608,
 'Escape Plan': 609,
 'The Legend of Hercules': 610,
 'The Sum of All Fears': 611,
 'The Twilight Saga: Eclipse': 612,
 'The Score': 613,
 'Despicable Me': 614,
 'Money Train': 615,
 'Ted 2': 616,
 'Agora': 617,
 'Mystery Men': 618,
 'Hall Pass': 619,
 'The Insider': 620,
 'The Finest Hours': 621,
 'Body of Lies': 622,
 'Dinner for Schmucks': 623,
 'Abraham Lincoln: Vampire Hunter': 624,
 'Entrapment': 625,
 'The X Files': 626,
 'The Last Legion': 627,
 'Saving Private Ryan': 628,
 'Need for Speed': 629,
 'What Women Want': 630,
 'Ice Age': 631,
 'Dreamcatcher': 632,
 'Lincoln': 633,
 'The Matrix': 634,
 'Apollo 13': 635,
 'The Santa Clause 2': 636,
 'Les Misérables': 637,
 "You've Got Mail": 638,
 'Step Brothers': 639,
 'The Mask of Zorro': 640,
 'Due Date': 641,
 'Unbroken': 642,
 'Space Cowboys': 643,
 'Cliffhanger': 644,
 'Broken Arrow': 645,
 'The Kid': 646,
 'World Trade Center': 647,
 'Mona Lisa Smile': 648,
 'The Dictator': 649,
 'Eyes Wide Shut': 650,
 'Annie': 651,
 'Focus': 652,
 'This Means War': 653,
 'Blade: Trinity': 654,
 'Red Dawn': 655,
 'Primary Colors': 656,
 'Resident Evil: Retribution': 657,
 'Death Race': 658,
 'The Long Kiss Goodnight': 659,
 'Proof of Life': 660,
 'Zathura: A Space Adventure': 661,
 'Fight Club': 662,
 'We Are Marshall': 663,
 'Hudson Hawk': 664,
 'Lucky Numbers': 665,
 'I, Frankenstein': 666,
 'Oliver Twist': 667,
 'Elektra': 668,
 'Sin City: A Dame to Kill For': 669,
 'Random Hearts': 670,
 'Everest': 671,
 'Perfume: The Story of a Murderer': 672,
 'Austin Powers in Goldmember': 673,
 'Astro Boy': 674,
 'Jurassic Park': 675,
 'Wyatt Earp': 676,
 'Clear and Present Danger': 677,
 'Dragon Blade': 678,
 'Little Man': 679,
 'U-571': 680,
 'The American President': 681,
 'The Love Guru': 682,
 '3000 Miles to Graceland': 683,
 'The Hateful Eight': 684,
 'Blades of Glory': 685,
 'Hop': 686,
 '300': 687,
 'Meet the Fockers': 688,
 'Marley & Me': 689,
 'The Green Mile': 690,
 'Wild Hogs': 691,
 'Chicken Little': 692,
 'Gone Girl': 693,
 'The Bourne Identity': 694,
 'GoldenEye': 695,
 "The General's Daughter": 696,
 'The Truman Show': 697,
 'The Prince of Egypt': 698,
 'Daddy Day Care': 699,
 '2 Guns': 700,
 'Cats & Dogs': 701,
 'The Italian Job': 702,
 'Two Weeks Notice': 703,
 'Antz': 704,
 'Couples Retreat': 705,
 'Days of Thunder': 706,
 'Cheaper by the Dozen 2': 707,
 'Maze Runner: The Scorch Trials': 708,
 'Eat Pray Love': 709,
 'The Family Man': 710,
 'RED': 711,
 'Any Given Sunday': 712,
 'The Horse Whisperer': 713,
 'Collateral': 714,
 'The Scorpion King': 715,
 'Ladder 49': 716,
 'Jack Reacher': 717,
 'Deep Blue Sea': 718,
 'This Is It': 719,
 'Contagion': 720,
 'Kangaroo Jack': 721,
 'Coraline': 722,
 'The Happening': 723,
 'Man on Fire': 724,
 'The Shaggy Dog': 725,
 'Starsky & Hutch': 726,
 'Jingle All the Way': 727,
 'Hellboy': 728,
 'A Civil Action': 729,
 'ParaNorman': 730,
 'The Jackal': 731,
 'Paycheck': 732,
 'Up Close & Personal': 733,
 'The Tale of Despereaux': 734,
 'The Tuxedo': 735,
 'Under Siege 2: Dark Territory': 736,
 'Jack Ryan: Shadow Recruit': 737,
 'Joy': 738,
 'London Has Fallen': 739,
 'Alien: Resurrection': 740,
 'Shooter': 741,
 'The Boxtrolls': 742,
 'Practical Magic': 743,
 'The Lego Movie': 744,
 'Miss Congeniality 2: Armed and Fabulous': 745,
 'Reign of Fire': 746,
 'Gangster Squad': 747,
 'Year One': 748,
 'Invictus': 749,
 'State of Play': 750,
 'Duplicity': 751,
 'My Favorite Martian': 752,
 'The Sentinel': 753,
 'Planet 51': 754,
 'Star Trek: Nemesis': 755,
 'Intolerable Cruelty': 756,
 'Trouble with the Curve': 757,
 'Edge of Darkness': 758,
 'The Relic': 759,
 'Analyze That': 760,
 'Righteous Kill': 761,
 'Mercury Rising': 762,
 'The Soloist': 763,
 'The Legend of Bagger Vance': 764,

In [246]:
def recommend_multiple(movie_list, similarity,top_n=5):
    indices = [movie_to_index[movie] for movie in movie_list if movie in movie_to_index]

    if not indices:
        return

    avg_similarity = np.mean(similarity[indices], axis=0)
    print(avg_similarity.shape)
    distances = sorted(
        list(enumerate(avg_similarity)),
        reverse=True,
        key=lambda x: x[1]
    )

    count = 0
    for idx, score in distances:
        if idx not in indices:
            print(movies.iloc[idx].title)
            count += 1

        if count == top_n:
            break

In [247]:
recommend_multiple(
    ["Interstellar", "Inception", "The Prestige"],
    similarity
)

(4800,)
Congo
Knowing
Extreme Ops
Solaris
Echo Dr.